[package]
name = "wasm-gc"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
parity-wasm = "0.15"
log = "0.3"
env_logger = { version = "0.4", default-features = false }
rustc-demangle = "0.1.5"
