[package]
name = "wasm-gc-cli"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[[bin]]
name = "wasm-gc"
path = "src/main.rs"

[dependencies]
wasm-gc = { path = "wasm-gc" }
env_logger = { version = "0.4", default-features = false }

[workspace]
